main: com.dropsistemi.dropsistemi
version: 1.0.0-SNAPSHOT
name: dropsistemi
author: Jarveus
api-version: 1.21
soft-depend: [MMOItems, MythicMobs, DecentHolograms, PlaceholderAPI]

commands:
  drop:
    description: Drop sistemi yonetim komutlari
    usage: /drop <reload|info|clear>
    permission: dropsistemi.admin
    permission-message: Bu komutu kullanma yetkiniz yok.

permissions:
  dropsistemi.admin:
    description: Tum drop sistemi komutlarina erisim
    default: op
    children:
      dropsistemi.reload: true
      dropsistemi.info: true
      dropsistemi.clear: true
  dropsistemi.reload:
    description: Config yeniden yukleme
    default: op
  dropsistemi.info:
    description: Aktif drop bilgisi
    default: op
  dropsistemi.clear:
    description: Tum droplari temizleme
    default: op